def start_log(): return 'started using the bot'
def newgame_log(): return 'started a new game'
def set_basic_log(): return 'set the game settings'
def set_advanced_log(): return 'set the prompts settings'
def feedback(): return 'send feedback'
def complain(): return 'complained'
def open_history_log(): return 'deactivated incognito mode'
def hide_history_log(): return 'activated incognito mode'
def reset_log(): return 'reset'
def english_log(): return 'set English'
def russian_log(): return 'set Russian'
def test_log(): return 'activated the test mode'
def info_log(): return 'learned info'
def past_log(): return 'learned past'
def time_log(): return 'learned average time'
def gpt_log(): return 'changed model to gpt'
def llama_log(): return 'changed model to llama'
def gemini_log(): return 'changed model to gemini'
